version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    ports:
      - 50051:50051
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    image: postgres:9.4
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codepix
      - PGDATA=/var/lib/postgresql/pgdata

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db